# Generated by Django 5.1.4 on 2024-12-17 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='digital',
        ),
    ]
