# Generated by Django 5.1.4 on 2025-03-21 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_remove_user_is_phone_verified_remove_user_otp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='size',
            field=models.JSONField(),
        ),
    ]
