# Generated by Django 5.1.4 on 2024-12-24 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_order_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='status',
            field=models.CharField(choices=[('not available', 'not available'), ('in stock', 'in stock')], default='in stock', max_length=100),
        ),
    ]
