# Generated by Django 5.1.4 on 2025-03-26 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_products_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
