# Generated by Django 5.1.4 on 2024-12-30 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_products_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='size',
            field=models.JSONField(default=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='products',
            name='stock',
            field=models.IntegerField(default=100),
        ),
    ]
