# Generated by Django 5.1.4 on 2024-12-30 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_shippingaddress_name_alter_products_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('NOT ACTIVE', 'NOT ACTIVE')], default='', max_length=100),
        ),
    ]
