# Generated by Django 5.1.4 on 2024-12-31 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_remove_order_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='status',
        ),
    ]
